"""Generate config.yaml from wizard choices.

The file is regenerated from a fully inline-documented template (the expert
layer points users here), validated through config.load_config before the old
file is replaced, and never contains a secret — keys go to .env.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

TEMPLATE = """\
# RAVE configuration — generated by `rave setup` (safe to edit by hand).
# Secrets do NOT belong here: the API key lives in .env (chmod 600) under the
# env var named by api_key_env.

llm:
  # mode local  = keyless; blank base_url means http://localhost:11434/v1
  # mode api    = hosted service; base_url required, key read from api_key_env
  # protocol is auto-detected: api.anthropic.com speaks Anthropic, every other
  # URL speaks OpenAI-compatible chat completions.
  mode: {llm_mode}
  base_url: "{base_url}"
  model: {model}
  api_key_env: {api_key_env}
  timeout_seconds: 120
  max_tokens: 4096
  temperature: 0.2

search:
  # metasearch = self-hosted SearXNG/search server [recommended]:
  #              community-maintained breadth (Google + Bing, ~200 engines)
  # scout      = built-in keyless multi-source search (zero-install fallback)
  # crawler    = built-in web reader over the trusted domain list below
  # commercial = keyed JSON search API (key env var: RAVE_SEARCH_API_KEY)
  # auto       = metasearch when a SearXNG answers (metasearch_url, else
  #              localhost:8080), else scout
  backend: {search_backend}
  scout:
    trusted_outlets: {trusted_outlets}
    sources: {{}}
    searxng_public: false
    offline: false
  metasearch_url: "{metasearch_url}"
  commercial:
    endpoint: "{commercial_endpoint}"
    api_key_env: RAVE_SEARCH_API_KEY
  crawler:
    domains: {crawler_domains}
    index_dir: .rave_index
    max_pages_per_domain: 50

pipeline:
  chunk_tokens: 400
  chunk_overlap: 50
  stale_months: 6
  max_fetch_per_search: 5
  embeddings:
    provider: hash
    base_url: ""
    model: ""

modes:
  speed:    {{researcher_iters: 2, critic_cycles: 0, tool_call_ceiling: 25}}
  balanced: {{researcher_iters: 4, critic_cycles: 1, tool_call_ceiling: 60}}
  quality:  {{researcher_iters: 8, critic_cycles: 3, tool_call_ceiling: 150}}
"""


@dataclass
class ConfigChoices:
    llm_mode: str = "local"                # local | api
    base_url: str = ""                     # blank in local mode = localhost default
    model: str = "llama3.1:8b"
    api_key_env: str = "RAVE_LLM_API_KEY"
    search_backend: str = "scout"          # scout | metasearch | crawler | commercial
    metasearch_url: str = ""
    commercial_endpoint: str = ""
    crawler_domains: list[str] = field(default_factory=list)
    trusted_outlets: list[str] = field(default_factory=list)


def render_config(choices: ConfigChoices) -> str:
    return TEMPLATE.format(
        llm_mode=choices.llm_mode,
        base_url=choices.base_url,
        model=choices.model,
        api_key_env=choices.api_key_env,
        search_backend=choices.search_backend,
        metasearch_url=choices.metasearch_url,
        commercial_endpoint=choices.commercial_endpoint,
        crawler_domains="[" + ", ".join(choices.crawler_domains) + "]",
        trusted_outlets="[" + ", ".join(choices.trusted_outlets) + "]",
    )


def write_config(path: str | Path, choices: ConfigChoices) -> None:
    """Validate the rendered config, then atomically replace the file."""
    from config import load_config

    p = Path(path)
    text = render_config(choices)
    tmp = p.with_suffix(".yaml.tmp")
    tmp.write_text(text, encoding="utf-8")
    try:
        cfg = load_config(tmp)  # raises on anything invalid
        assert cfg.llm.mode == choices.llm_mode
    except Exception:
        tmp.unlink(missing_ok=True)
        raise
    tmp.replace(p)
