"""Step 3 — web reach: SearXNG via Docker when possible, else the built-in
crawler over a user-trusted domain list.
"""
from __future__ import annotations

import secrets
from pathlib import Path
from typing import Callable

SEARXNG_PORT = 8080
SEARXNG_CONTAINER = "rave-searxng"

# Sites offered when the user presses Enter for "good defaults" in crawler mode.
DEFAULT_TRUSTED = [
    "en.wikipedia.org",
    "www.bbc.com",
    "www.who.int",
    "www.nih.gov",
]

SEARXNG_SETTINGS = """\
# Generated by rave setup — enables the JSON API RAVE needs.
use_default_settings: true
server:
  secret_key: "{secret}"
search:
  formats:
    - html
    - json
"""


def searxng_url() -> str:
    return f"http://localhost:{SEARXNG_PORT}"


def start_searxng(
    repo: Path,
    run: Callable,
    http_get: Callable[[str], object],
    sleep: Callable[[float], None],
    poll_tries: int = 15,
) -> str | None:
    """Start (or restart) the SearXNG container; return its URL when the JSON
    API answers, else None."""
    settings_dir = repo / ".rave" / "searxng"
    settings_dir.mkdir(parents=True, exist_ok=True)
    settings = settings_dir / "settings.yml"
    if not settings.exists():
        settings.write_text(
            SEARXNG_SETTINGS.format(secret=secrets.token_hex(16)),
            encoding="utf-8",
        )
    run(["docker", "rm", "-f", SEARXNG_CONTAINER])  # idempotent restart
    code, out = run([
        "docker", "run", "-d", "--name", SEARXNG_CONTAINER,
        "-p", f"{SEARXNG_PORT}:8080",
        "-v", f"{settings_dir}:/etc/searxng",
        "--restart", "unless-stopped",
        "searxng/searxng",
    ])
    if code != 0:
        return None
    probe = f"{searxng_url()}/search?q=hello&format=json"
    for _ in range(poll_tries):
        try:
            resp = http_get(probe)
            if getattr(resp, "status_code", 0) == 200:
                return searxng_url()
        except Exception:  # noqa: BLE001 — container still starting
            pass
        sleep(2.0)
    return None


def parse_trusted_domains(raw: str) -> list[str]:
    """Free-text domain list → cleaned domains; empty input → good defaults."""
    if not raw.strip():
        return list(DEFAULT_TRUSTED)
    parts = [p.strip().rstrip("/") for p in raw.replace(",", " ").split()]
    domains = []
    for p in parts:
        p = p.removeprefix("https://").removeprefix("http://")
        if p and "." in p and p not in domains:
            domains.append(p)
    return domains or list(DEFAULT_TRUSTED)
