"""Source vetting: classify source type, weight quality, apply staleness.

Everything here is deterministic heuristics over the URL, title, text, and
date — no LLM judgment. Primary/official/peer-reviewed sources are ranked up;
SEO farms, undated pages, and anonymous forum content are down-weighted or
dropped. The staleness rule applies only to fast-moving topics: sources older
than the configured window are flagged `[stale]` and down-weighted.
"""
from __future__ import annotations

import datetime as _dt
from collections import Counter
from dataclasses import dataclass
from urllib.parse import urlsplit

from llm.schemas import SourceType, TopicKind
from tools.extractor import parse_date
from tools.ranker import tokenize

TYPE_WEIGHT: dict[SourceType, float] = {
    SourceType.primary: 1.30,
    SourceType.official: 1.25,
    SourceType.peer_reviewed: 1.25,
    SourceType.news: 1.00,
    SourceType.analyst: 0.95,
    SourceType.blog: 0.80,
    SourceType.forum: 0.65,
    SourceType.ai_generated: 0.40,
}

_AI_MARKERS = ("as an ai language model", "generated by artificial intelligence")


def classify_source(url: str, title: str = "", text: str = "") -> SourceType:
    """Heuristic source-type classification from URL shape and content."""
    parts = urlsplit(url)
    host = parts.netloc.lower()
    path = parts.path.lower()
    lower_text = text[:2000].lower()

    if any(m in lower_text for m in _AI_MARKERS):
        return SourceType.ai_generated
    tld_bits = host.rsplit(":", 1)[0].split(".")
    if any(b in ("gov", "mil", "int") for b in tld_bits[-2:]):
        return SourceType.official
    if any(b in ("edu", "ac") for b in tld_bits[-3:]) or "doi" in host or "/doi/" in path:
        return SourceType.peer_reviewed
    if "journal" in host or "/journal" in path or "/paper" in path:
        return SourceType.peer_reviewed
    if host.startswith(("docs.", "developer.", "support.")) or path.startswith(
        ("/docs", "/documentation", "/spec", "/manual", "/legal", "/pricing", "/press")
    ):
        return SourceType.primary
    if "forum" in host or "forum" in path or "/thread" in path or "/t/" in path or "community." in host:
        return SourceType.forum
    if "blog" in host or "/blog" in path or "/posts/" in path or "newsletter" in host:
        return SourceType.blog
    if "research" in host or "/research" in path or "analyst" in lower_text[:400]:
        return SourceType.analyst
    if host.startswith("news.") or "/news" in path or "/article" in path or "/story" in path:
        return SourceType.news
    return SourceType.news if "/20" in path else SourceType.blog


def seo_farm_score(title: str, text: str) -> float:
    """0 (clean) → 1 (obvious SEO farm): keyword stuffing + repetition."""
    toks = tokenize(text)
    if len(toks) < 40:
        return 0.0
    counts = Counter(toks)
    top_ratio = counts.most_common(1)[0][1] / len(toks)
    stuffing = min(1.0, max(0.0, (top_ratio - 0.05) / 0.10))
    title_toks = tokenize(title)
    title_spam = 0.0
    if title_toks:
        title_repeat = max(Counter(title_toks).values()) / len(title_toks)
        title_spam = min(1.0, max(0.0, (title_repeat - 0.34) / 0.5))
    return max(stuffing, title_spam)


@dataclass
class VetVerdict:
    source_type: SourceType
    weight: float          # multiplier applied to relevance score
    stale: bool
    drop: bool
    reasons: list[str]


def vet(
    url: str,
    title: str = "",
    text: str = "",
    date_str: str = "",
    topic_kind: TopicKind = TopicKind.fast_moving,
    stale_months: int = 6,
    today: _dt.date | None = None,
) -> VetVerdict:
    stype = classify_source(url, title, text)
    weight = TYPE_WEIGHT[stype]
    reasons: list[str] = [f"type:{stype.value}"]
    drop = False

    farm = seo_farm_score(title, text)
    if farm >= 0.9:
        drop = True
        reasons.append("drop:seo_farm")
    elif farm > 0.4:
        weight *= 0.5
        reasons.append("downrank:seo_signals")

    pub = parse_date(date_str)
    if pub is None:
        weight *= 0.85
        reasons.append("downrank:undated")

    stale = False
    if pub is not None and topic_kind == TopicKind.fast_moving:
        today = today or _dt.date.today()
        age_days = (today - pub).days
        if age_days > stale_months * 30:
            stale = True
            weight *= 0.6
            reasons.append("downrank:stale")

    if stype == SourceType.ai_generated:
        drop = True
        reasons.append("drop:ai_generated")

    return VetVerdict(stype, round(weight, 4), stale, drop, reasons)
